# Generated by Django 3.0.7 on 2021-08-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_auto_20210822_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='cost_of_product',
        ),
    ]
