# Generated by Django 3.0.7 on 2021-08-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0008_auto_20210822_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtime',
            name='work_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.WorkDay'),
        ),
    ]
