# Generated by Django 3.0.7 on 2021-08-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0011_auto_20210823_0706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='OrderExpense',
        ),
        migrations.RenameField(
            model_name='workerexpense',
            old_name='date_payd',
            new_name='date_paid',
        ),
    ]
