# Generated by Django 3.0.7 on 2021-08-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0012_auto_20210823_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='starting_at',
            field=models.DateField(verbose_name='Started at'),
        ),
    ]
