# Generated by Django 3.0.7 on 2021-09-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0013_auto_20210823_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='balance',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='starting_at',
            field=models.DateField(),
        ),
    ]
