# Generated by Django 3.0.7 on 2021-09-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0014_auto_20210903_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='starting_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
