# Generated by Django 3.0.7 on 2021-09-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0016_auto_20210903_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
