# Generated by Django 3.0.7 on 2021-09-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0020_auto_20210903_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='began_at',
            field=models.DateField(blank=True, default='2021-05-07', null=True),
        ),
    ]
