# Generated by Django 3.0.7 on 2021-09-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0021_auto_20210903_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='taxes_amount_per_day',
            field=models.FloatField(default=8.8),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
