# Generated by Django 3.0.7 on 2021-09-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0022_auto_20210904_1159'),
    ]

    operations = [
    ]
