# Generated by Django 3.0.7 on 2021-09-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0025_workerexpense_assigned_to_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='balance',
        ),
        migrations.AddField(
            model_name='workingtime',
            name='calculated_pay',
            field=models.FloatField(default=0),
        ),
    ]
