# Generated by Django 3.0.7 on 2021-09-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0026_auto_20210904_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='calculated_pay',
            field=models.FloatField(default=None, editable=False),
        ),
    ]
