# Generated by Django 3.0.7 on 2021-09-04 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0027_auto_20210904_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='taxes_amount_per_day',
            new_name='taxes_amount_per_hour',
        ),
    ]
