# Generated by Django 3.0.7 on 2021-09-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0028_auto_20210904_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtime',
            name='worked_on',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
