# Generated by Django 3.0.7 on 2021-09-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0029_workingtime_worked_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='worked_on',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
