# Generated by Django 3.0.7 on 2021-09-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0034_orderexpense_calculated_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderexpense',
            name='calculated_expense',
            field=models.FloatField(editable=False),
        ),
    ]
