# Generated by Django 3.0.7 on 2021-09-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0035_auto_20210908_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderexpense',
            name='amount_payd',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
