# Generated by Django 3.0.7 on 2021-09-19 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0036_orderexpense_amount_payd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderexpense',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='construction.Product'),
        ),
    ]
