# Generated by Django 3.0.7 on 2021-09-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0039_auto_20210919_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderexpense',
            name='fixed_price_item',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
