# Generated by Django 3.0.7 on 2021-09-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0041_orderexpense_date_payd'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='date_formated',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
