# Generated by Django 3.0.7 on 2021-10-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0043_order_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderexpense',
            old_name='date_payd',
            new_name='date_paid',
        ),
    ]
