# Generated by Django 3.0.7 on 2021-10-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0044_auto_20211019_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderexpense',
            old_name='amount_payd',
            new_name='amount_paid',
        ),
    ]
