# Generated by Django 3.0.7 on 2022-03-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0045_auto_20211019_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='workingtime',
            name='workers',
            field=models.ManyToManyField(to='construction.Worker'),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='construction.Worker'),
        ),
    ]
