# Generated by Django 3.0.7 on 2022-03-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0046_auto_20220323_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='calculated_pay',
            field=models.FloatField(blank=True, default=None, editable=False, null=True),
        ),
    ]
