# Generated by Django 3.0.7 on 2022-03-24 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0048_auto_20220324_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkeringTimeOnOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Order')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Worker')),
            ],
        ),
    ]
